### ISSUE TITLE
[Issue] ControlNet Support

### ISSUE THREAD

**Issue by paulo-coronado** [dbolya/tomesd#9]
**ToMe** is currently not working with **ControlNet**. I tried canny preprocessor, for example, and got the following error:
```
TypeError: cannot unpack non-iterable NoneType object
```
Now, I am not sure if **sd-web-ui-controlnet** doesn't support **ToMe** or the opposite... 🤔

**Comment by AmanKishore** [comment]
Getting this error:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 235, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/usr/local/lib/python3.9/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/usr/local/lib/python3.9/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/root/render-engine.py", line 448, in gen_render
    final_image, nsfw_result = self.canvas_to_image(
  File "/root/render-engine.py", line 343, in canvas_to_image
    image = self.pipe_canny(
  File "/usr/local/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/sag/pipeline_sag_controlnet.py", line 1002, in __call__
    noise_pred = self.unet(
  File "/usr/local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/diffusers/models/unet_2d_condition.py", line 620, in forward
    sample, res_samples = downsample_block(
  File "/usr/local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/diffusers/models/unet_2d_blocks.py", line 837, in forward
    hidden_states = attn(
  File "/usr/local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/diffusers/models/transformer_2d.py", line 265, in forward
    hidden_states = block(
  File "/usr/local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/tomesd/patch.py", line 84, in forward
    m_a, m_c, m_m, u_a, u_c, u_m = compute_merge(hidden_states, self._tome_info)
  File "/usr/local/lib/python3.9/site-packages/tomesd/patch.py", line 11, in compute_merge
    original_h, original_w = tome_info["size"]
TypeError: cannot unpack non-iterable NoneType object
```

**Comment by dbolya** [comment]
ControlNet might patch the same things that ToMe patches, causing a conflict.
Can someone find which line is causing that TypeError? I haven't used ControlNet before.

**Comment by AmanKishore** [comment]
Stack trace:
```
  File "/root/sag/pipeline_stable_diffusion_controlnet.py", line 947, in __call__
    noise_pred = self.unet(
  File "/usr/local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/diffusers/models/unet_2d_condition.py", line 620, in forward
    sample, res_samples = downsample_block(
  File "/usr/local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/diffusers/models/unet_2d_blocks.py", line 837, in forward
    hidden_states = attn(
  File "/usr/local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/diffusers/models/transformer_2d.py", line 265, in forward
    hidden_states = block(
  File "/usr/local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/tomesd/patch.py", line 84, in forward
    m_a, m_c, m_m, u_a, u_c, u_m = compute_merge(hidden_states, self._tome_info)
  File "/usr/local/lib/python3.9/site-packages/tomesd/patch.py", line 11, in compute_merge
    original_h, original_w = tome_info["size"]
TypeError: cannot unpack non-iterable NoneType object
```

**Comment by dbolya** [comment]
Hmm, seems like the controlnet plugin might overwrite the forward function for the unet itself, which is how ToMe gets the image size. I'll try to see if I can find a workaround.

**Comment by dbolya** [comment]
Fixed this by changing how I patched the model. However, do note that controlnet runs its own model in parallel, and that model doesn't have tome applied. So the speed-up might not be as good as without using controlnet.

If there are any more issues, feel free to reopen.

**Comment by papuSpartan** [comment]
@icech 
It's up to the extension author whether they will add it, It's not a problem with tomesd.
